feat(datapoints-graph): refactor workflow to iterate over shells
Workflow iterate over shell versions

n/a

diff --git a/.github/workflows/collect-shell-versions.yml b/.github/workflows/collect-shell-versions.yml
--- a/.github/workflows/collect-shell-versions.yml
+++ b/.github/workflows/collect-shell-versions.yml
@@ -12,7 +12,8 @@ jobs:
   collect-shell-versions:
     timeout-minutes: 30
     runs-on: ubuntu-22.04
-    name: Get shell versions by tags
+    outputs:
+      non_deprecated_shell_versions: ${{ steps.collect-shell-versions.outputs.non_deprecated_shell_versions }}
 
     steps:
       - name: Checkout
@@ -47,21 +48,45 @@ jobs:
           cp -r dist/sag-pkg-community-plugins/* dist/apps/sag-pkg-community-plugins
 
       - name: Get @c8y/ngx-components, non-deprecated dist versions
-        id: check-deprecated
+        id: collect-shell-versions
         run: npm run collect-shell-versions
 
-      - name: Use non-deprecated versions
+      - name: Extract versions
+        id: extract-versions
         run: |
-          echo "Non-deprecated Versions: ${{ steps.check-deprecated.outputs.non_deprecated_shell_versions }}"
+          echo "::set-output name=non_deprecated_shell_versions::${{steps.collect-shell-versions.outputs.non_deprecated_shell_versions}}"
 
-      # TODO: further should run in loop for each shell version
+  use-shell-versions:
+    needs: collect-shell-versions
+    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        version_data: ${{ fromJson(needs.collect-shell-versions.outputs.non_deprecated_shell_versions) }}
+    env:
+      JSON: ${{ toJson(matrix.version_data) }}
+      VERSION: ${{ matrix.version_data.version }}
+      MAJOR: ${{ matrix.version_data.major }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18'
+          cache: 'npm'
+
+      - name: Install dependencies
+        run: npm ci
 
       - name: Get shell app of particular version
         run: |
           set -e  # Exit the script if any command fails
           # Extract the 'next' tag version from the JSON
-          json='${{ steps.check-deprecated.outputs.non_deprecated_shell_versions }}'
-          next_version=$(echo $json | jq -r '.next')
+          next_version="${{ env.VERSION }}"
           echo "Version is: $next_version"
 
           # Construct the file URL
@@ -72,8 +97,8 @@ jobs:
           echo "Downloading file..."
           curl -O $file_url
           if [ ! -f "apps-${next_version}.tgz" ]; then
-          echo "Downloaded file not found!"
-          exit 1
+            echo "Downloaded file not found!"
+            exit 1
           fi
           echo "Downloaded file exists."
 
@@ -81,8 +106,8 @@ jobs:
           echo "Extracting downloaded file..."
           tar -xzf "apps-${next_version}.tgz"
           if [ $? -ne 0 ]; then
-          echo "Extraction failed!"
-          exit 1
+            echo "Extraction failed!"
+            exit 1
           fi
           echo "File extracted successfully."
 
@@ -93,8 +118,8 @@ jobs:
 
           unzip -qq "$cockpit_file" -d "$destination_folder"
           if [ $? -ne 0 ]; then
-          echo "Extracting cockpit file failed!"
-          exit 1
+            echo "Extracting cockpit file failed!"
+            exit 1
           fi
           echo "Cockpit file extracted successfully."
 
@@ -111,7 +136,7 @@ jobs:
           browser: chrome
           record: false
           config-file: cypress.config.ts
-          env: C8Y_CTRL_MODE=mocking,grepTags=@1020
+          env: C8Y_CTRL_MODE=mocking,grepTags=@${{ env.MAJOR }}
 
       - name: Upload cypress screenshots
         uses: actions/upload-artifact@v3
