feat(ci): tests against shell workflow
cache create job fix

n/a

diff --git a/.github/workflows/test-plugins-against-cockpit.yml b/.github/workflows/test-plugins-against-cockpit.yml
--- a/.github/workflows/test-plugins-against-cockpit.yml
+++ b/.github/workflows/test-plugins-against-cockpit.yml
@@ -212,7 +212,7 @@ jobs:
       - name: Setup cache directory
         run: mkdir -p ./cache-files
 
-      - name: Download updated JSON files
+      - name: Download and unzip updated JSON files
         run: |
           shell_records=$(jq <<< '${{ needs.collect-shell-versions.outputs.shell_versions }}')
           plugins_version='${{ needs.collect-shell-versions.outputs.plugins_version }}'
@@ -224,12 +224,14 @@ jobs:
             tag=$(_jq '.tag')
             version=$(_jq '.version')
 
-            artifact_name=updated-json-$tag-$version-$plugins_version
+            artifact_name=updated-json-$tag-$version-$plugins_version.zip
 
             echo "Downloading artifact $artifact_name"
             mkdir -p ./cache-files
-            echo "Retrieving: ${artifact_name}"
-            actions/download-artifact@v4 --name $artifact_name --path ./cache-files || echo "Failed to fetch artifact: $artifact_name"
+            actions/download-artifact@v4 --name "updated-json-$tag-$version-$plugins_version" --path ./cache-files || echo "Failed to fetch artifact: $artifact_name"
+
+            echo "Unzipping artifact $artifact_name"
+            unzip ./cache-files/"$artifact_name" -d ./cache-files
           done
 
       - name: Upload to cache
